### ISSUE TITLE
Can't Connect to EKS

### ISSUE THREAD

**Issue by kferrone** [de-jcup/ekube#54]
We are using an EKS cluster with AWS and this plugin can't connect to it at all. Here is the error: 

```
An internal error occurred during: "connect to kubernetes - use context:arn:aws:eks:us-west-2:123456789:cluster/myclusterid".
Failure executing: GET at: https://bigid.yl4.us-west-2.eks.amazonaws.com/api/v1/namespaces. Message: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=namespaces, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
```

It says I'm using the anonymous user and therefore I am forbidden to list namespaces. My config was set up by the the aws cli which is definitely correct as I am able to do everything from the command line. Any ideas why this plugin is using a different user than the config says to use?

**Comment by de-jcup** [comment]
Hello @kferrone ,

Please look into preferences - at the first line you see the path used to lookup for kubectl config file

![image](https://user-images.githubusercontent.com/11644753/74707399-0a150b00-521a-11ea-9dc6-e512504885ed.png)

This is the config file which is used by ekube to connect with your k8s.

Maybe your config file is not on default path - please check the path your AWS cli uses and update the path inside the preferences.

Hope this helps.

**Comment by kferrone** [comment]
It is pointing to my correct config file. 

I feel it has to do with the user section:
```yaml
users:
- name: arn:aws:eks:us-west-123456:cluster/mycluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - mycluster
      - --role
      - arn:aws:iam::12345:role/mystackadmin
      command: aws
      env: null
```

The command  will return a manifest of kind `ExecCredential`. Seems ekube doesn't handle it correctly.

**Comment by de-jcup** [comment]
I am using Fabric8 libraries to connect and request k8s
currently "io.fabric8:kubernetes-client:4.1.0"

Fabric8ioEKubeModelBuilder.java:
```java
import io.fabric8.kubernetes.api.model.DoneableNamespace;
import io.fabric8.kubernetes.api.model.Namespace;
import io.fabric8.kubernetes.api.model.NamespaceList;
import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.dsl.NonNamespaceOperation;
import io.fabric8.kubernetes.client.dsl.Resource;
...
  @Override
  public EKubeModel build(EKubeContext context) {
       ....
         Config config = Config.autoConfigure(wantedKubernetesContext);
       ...
```
So configuration and connect is done completely by fabric8 libraries and using Config.autoConfigure

I connect by following way and it works:
```yaml
users:
- name: xyz-admin
  user:
    client-certificate-data: blabla1234...long..certificate..blabla
    client-key-data: blabla1234...long..client-key..blabla
```

## Possible solutions
### Just upgrade version of fabric8
I could try to update to fabbric8 4.8.0 - see
https://mvnrepository.com/artifact/io.fabric8/kubernetes-client/4.8.0

But having no access to same setup as yours, I cannot test
### You do some research and give me feedback
https://github.com/fabric8io/kubernetes-client
is the OSS project. Maybe you could just tryout if a simple "hello connect" like in
https://github.com/fabric8io/kubernetes-client#usage in combination with Config.autoConfigure(String); works with your setup.
If not you could create an issue there. If its fixed I would integrate the new library version.

**Comment by kferrone** [comment]
So I have no idea how to actually update this plugin or do anything to Fabric8. Maybe one day when I have time . . . However I did figure out that this plugin will only accept a user with certs and tokens like below:

using certs is ok
```yaml
user:
  client-certificate-data: . . . 
  client-key-data: . . .
```

using token is ok
```yaml
user:
  token: . . . 
```

The following log-in options will not work however:

using tokenFile will not work
```yaml
user:
  tokenFile: . . . 
```

using exec will not work either:
```yaml
user:
  apiVersion: client.authentication.k8s.io/v1alpha1
  command: someCommandForToken
  args: . . . 
```

At least I can use this plugin now! 😊
